version: '2'

services:
  app:
    image: 'marketapi:latest'
    ports:
      - 0.0.0.0:80:8080
    build:
      context: .
    container_name: app
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/marketdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:latest'
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=marketdb
    volumes:
      - /home/ubuntu/postgresData:/var/lib/postgresql/data
